defaults:
  # RL paramters
  maxUpdates: 200000
  memoryCapacity: 500000
  checkPeriod: 10000
  tau: 0.005
  actor_lr: 1e-4
  critic_lr: 1e-4

  use_ensemble: True
  use_unit_ensemble: False 
  use_nf: False
  use_uq: True
  action_reg: False
  model_free: False
  remark: 'test'
  rand_action: False
  model_path: null
  offline_traindir: [
  ]
  reachability_batch_size: 512
  reachability_model_path: ''
  gamma_reachability: 0.95
  ood_threshold: 4.0
  control_net: [512, 512, 512, 512]
  critic_net: [512, 512, 512, 512]
  stochastic_l: False

  logdir: "latent_safety/reachability_dreamer/logs"
  traindir: null
  evaldir: null
  offline_evaldir: ''
  seed: 0
  deterministic_run: True
  steps: 1e6
  parallel: False
  eval_every: 500
  eval_num_seeds: 50
  eval_per_seed: 1
  log_every: 50
  log_every_video: 500
  reset_every: 0
  device: 'cuda'
  compile: True
  precision: 32
  debug: False
  video_pred_log: True
  from_ckpt: null
  lx_ckpt: null
  num_actions: 7
  from_prefill_dir: null
  obs_step: 1

  # Environment
  task: 'Isaac-Takeoff-Franka-IK-Rel-v0'
  size: [128, 128]
  envs: 1
  action_repeat: 2
  time_limit: 1000
  grayscale: False
  prefill: 2500
  reward_EMA: True

  # Model
  dyn_hidden: 512
  dyn_deter: 512
  dyn_stoch: 32
  dyn_discrete: 32 # set as 0 for continuous latent  #32
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['decoder', 'reward', 'cont', 'failure']
  units: 512
  act: 'SiLU'
  norm: True
  encoder:
    {mlp_keys: '^eef_(pos|quat)$', cnn_keys: '.*\_cam$', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, symlog_inputs: True}
  decoder:
    {mlp_keys: '^eef_(pos|quat)$', cnn_keys: '.*\_cam$', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, cnn_sigmoid: False, image_dist: mse, vector_dist: symlog_mse, outscale: 1.0}
  actor:
    {layers: 2, dist: 'normal', entropy: 3e-4, unimix_ratio: 0.01, std: 'learned', min_std: 0.1, max_std: 1.0, temp: 0.1, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 1.0}
  critic:
    {layers: 2, dist: 'symlog_disc', slow_target: True, slow_target_update: 1, slow_target_fraction: 0.02, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 0.0}
  reward_head:
    {layers: 2, dist: 'symlog_disc', loss_scale: 1.0, outscale: 0.0}
  cont_head:
    {layers: 2, loss_scale: 1.0, outscale: 1.0}
  failure_head:
    {layers: 2, loss_scale: 1.0, outscale: 1.0}
  dyn_scale: 0.5
  rep_scale: 0.1
  kl_free: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  initial: 'learned'

  # Training
  batch_size: 16
  batch_length: 16
  train_ratio: 512
  pretrain: 100
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  dataset_size: 1000000
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 15
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.0
  eval_state_mean: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'deter'
  disag_log: True
  disag_models: 5 #10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: True

debug:
  debug: True
  pretrain: 1
  prefill: 1
  batch_size: 10
  batch_length: 20